---
- name: Redhat | get git repository rpm
# Redhat based OS
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present
  become: yes
  tags:
    - git repository
    - install
    - packages

- name: Redhat | yum install git2u-all
  yum:
    name: 
      - "git2u-all"
    state: present
  become: yes
  notify:
    - start git
  tags:
    - git
    - install
    - packages

